Css
the-vaan-group/guides pull request #3
Opened 2022-10-27 18:53 UTC by federicocastanon

Added a section for CSS with basic content that needs to be expanded upon

2022-11-02 14:35 UTC, raymall requested changes
- We use a mobile-first approach.
- I think we don't need to mention Gulp.js
- We use SASS
- We recommend responsive scaling

2022-11-07 13:16 UTC, federicocastanon commented
> * We use a mobile-first approach.
> * I think we don't need to mention Gulp.js
> * We use SASS
> * We recommend responsive scaling

Addressed

2022-11-08 10:01 UTC, illarionvk requested changes
Plese rename `CSS` folder to `css` because all folder names should be lowercase in `kebab-case` format.

2022-11-08 10:01 UTC, illarionvk commented on CSS/README.md
> +- We recommend responsive scaling
Unclear recommendation, let's revisit it in the next round.

```suggestion
```

2022-11-08 16:59 UTC, federicocastanon commented on CSS/README.md
> +- Use [viewport](https://www.w3schools.com/css/css_rwd_viewport.asp)
What about [this one](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag) from Mozilla?

2022-11-16 18:46 UTC, federicocastanon commented
@illarionvk 's comments have been addressed

2022-11-18 17:03 UTC, illarionvk approved these changes

2022-11-18 17:05 UTC, merged